"""
CORTEX — Core Data Models
Defines the data structures that flow between agents.
"""

from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime
from typing import Optional
import uuid
import json


class Side(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class Decision(str, Enum):
    APPROVED = "APPROVED"
    VETOED = "VETOED"


class AgentRole(str, Enum):
    STRATEGIST = "strategist"
    RISK_OFFICER = "risk_officer"
    EXECUTOR = "executor"
    COMPLIANCE = "compliance"
    AUDITOR = "auditor"


class EventType(str, Enum):
    PROPOSAL = "trade_proposal"
    RISK_ASSESSMENT = "risk_assessment"
    EXECUTION = "trade_execution"
    COMPLIANCE_CHECK = "compliance_check"
    COMPLIANCE_ALERT = "compliance_alert"
    AUDIT_LOG = "audit_log"
    CIRCUIT_BREAKER = "circuit_breaker"
    SYSTEM = "system"


@dataclass
class TradeProposal:
    """Generated by the Strategist Agent."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    asset: str = ""
    side: Side = Side.LONG
    size_usd: float = 0.0
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    rationale: str = ""
    confidence: float = 0.0  # 0-1
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    signals: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "asset": self.asset,
            "side": self.side.value,
            "size_usd": self.size_usd,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "rationale": self.rationale,
            "confidence": self.confidence,
            "timestamp": self.timestamp,
            "signals": self.signals,
        }


@dataclass
class RiskAssessment:
    """Generated by the Risk Officer Agent."""
    proposal_id: str = ""
    decision: Decision = Decision.VETOED
    reasoning: str = ""
    risk_score: float = 0.0  # 0-10, 10 = max risk
    max_drawdown_pct: float = 0.0
    position_size_ok: bool = False
    correlation_ok: bool = False
    exposure_after: float = 0.0  # total portfolio exposure after trade
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_dict(self) -> dict:
        return {
            "proposal_id": self.proposal_id,
            "decision": self.decision.value,
            "reasoning": self.reasoning,
            "risk_score": self.risk_score,
            "max_drawdown_pct": self.max_drawdown_pct,
            "position_size_ok": self.position_size_ok,
            "correlation_ok": self.correlation_ok,
            "exposure_after": self.exposure_after,
            "timestamp": self.timestamp,
        }


@dataclass
class TradeExecution:
    """Generated by the Executor Agent."""
    proposal_id: str = ""
    success: bool = False
    executed_price: float = 0.0
    executed_size: float = 0.0
    order_id: str = ""
    exchange: str = "kraken"
    fees: float = 0.0
    slippage_bps: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_dict(self) -> dict:
        return {
            "proposal_id": self.proposal_id,
            "success": self.success,
            "executed_price": self.executed_price,
            "executed_size": self.executed_size,
            "order_id": self.order_id,
            "exchange": self.exchange,
            "fees": self.fees,
            "slippage_bps": self.slippage_bps,
            "timestamp": self.timestamp,
        }


@dataclass
class ComplianceCheck:
    """Generated by the Compliance Agent."""
    proposal_id: str = ""
    all_clear: bool = True
    total_exposure_pct: float = 0.0
    daily_pnl_pct: float = 0.0
    open_positions: int = 0
    alerts: list = field(default_factory=list)
    circuit_breaker_triggered: bool = False
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_dict(self) -> dict:
        return {
            "proposal_id": self.proposal_id,
            "all_clear": self.all_clear,
            "total_exposure_pct": self.total_exposure_pct,
            "daily_pnl_pct": self.daily_pnl_pct,
            "open_positions": self.open_positions,
            "alerts": self.alerts,
            "circuit_breaker_triggered": self.circuit_breaker_triggered,
            "timestamp": self.timestamp,
        }


@dataclass
class CortexEvent:
    """Universal event that flows through the system."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    event_type: EventType = EventType.SYSTEM
    agent: AgentRole = AgentRole.STRATEGIST
    data: dict = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "event_type": self.event_type.value,
            "agent": self.agent.value,
            "data": self.data,
            "timestamp": self.timestamp,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)
